Repository coder2hacker/explore-open-source-hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#4 process
  Process Notes (2) (2).pdf
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#7 Created sign up page
  .gitignore
  HTML-Animation-main/HTML-Animation-main/1.gif
  HTML-Animation-main/HTML-Animation-main/2.gif
  HTML-Animation-main/HTML-Animation-main/3.gif
  HTML-Animation-main/HTML-Animation-main/4.gif
  HTML-Animation-main/HTML-Animation-main/Animation.html
  HTML-Animation-main/HTML-Animation-main/README.md
  HTML-Animation-main/HTML-Animation-main/bg.jpg
  HTML-Animation-main/HTML-Animation-main/birds.gif
  Login-Page--main/Login-Page--main/README.md
  Login-Page--main/Login-Page--main/bg.jpg
  Login-Page--main/Login-Page--main/login.html
  Scooter-Animation-main/Scooter-Animation-main/README.md
  Scooter-Animation-main/Scooter-Animation-main/S.HTML
  birthday-master/birthday-master/Balloon-Border.png
  birthday-master/birthday-master/LICENSE
  birthday-master/birthday-master/README.md
  birthday-master/birthday-master/b1.png
  birthday-master/birthday-master/b2.png
  birthday-master/birthday-master/b3.png
  birthday-master/birthday-master/b4.png
  birthday-master/birthday-master/b5.png
  birthday-master/birthday-master/b6.png
  birthday-master/birthday-master/b7.png
  birthday-master/birthday-master/banner.png
  birthday-master/birthday-master/bd1.jpg
  birthday-master/birthday-master/bulb.png
  birthday-master/birthday-master/bulb_blue.png
  birthday-master/birthday-master/bulb_green.png
  birthday-master/birthday-master/bulb_orange.png
  birthday-master/birthday-master/bulb_pink.png
  birthday-master/birthday-master/bulb_red.png
  birthday-master/birthday-master/bulb_yellow.png
  birthday-master/birthday-master/cake.less
  birthday-master/birthday-master/cake128.png
  birthday-master/birthday-master/effect.js
  birthday-master/birthday-master/favicon.ico
  birthday-master/birthday-master/hbd.mp3
  birthday-master/birthday-master/index.html
  birthday-master/birthday-master/loading.css
  birthday-master/birthday-master/package-lock.json
  birthday-master/birthday-master/package.json
  birthday-master/birthday-master/stylesheet.css
  birthday-master/birthday-master/uggreen.png
  birthday-master/birthday-master/vine.png
  sign-up/README.md
  sign-up/image-1.jpg
  sign-up/signup.html
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#6 Meeting prompt
  apis-meeting-prompt.txt
  chatgpt-vs-bard-vs-bing.pdf
  project-with-copilot-chat.zip
  rename_files.py
  sales_data.csv
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#8 adding file
  index.css
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#9 OpenAI
  OpenAI-scaled.jpeg
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#10 Add files via upload
  What-is-Full-Stack-Develo.9187520.powerpoint.pptx
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#11 ChatGPT_API_openai
  ChatGPT_API_openai.pdf
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#12 aws resources for the devops engineer
  aws_docs.pdf
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#13 Java Cheat Sheet
  Java Cheat Sheet.pdf
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#14 Think Python
  Think Python.pdf
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved, hacktoberfest2023-accepted

#17 initially
  TryThelon/index.html
  TryThelon/style.css
Labels: good first issue, hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#16 hello
  3n - 1 program.py
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#15 General Documentation
  Note.txt
Labels: hacktoberfest2023, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#18 aws overview
  AWS_Overview.pdf
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#19 Add files via upload
  aws-for-beginners.pdf
Labels: good first issue, hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#22 Create turtle.py
  turtle.py
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#20 Dart Program that can parse and manipulate JSON data
  Dart Programs/HTTPRequest.dart
  Dart Programs/JSONHandler.dart
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#23 Create editDistance.java
  editDistance.java
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED

#24 Update README.md
  README.md
Labels: hacktoberfest2023, hacktoberfest-approved, hacktoberfest2023-accepted, HACKTOBERFEST-ACCEPTED
